[tool.poetry]
name = "auto-testing-python"
version = "0.1.0"
description = ""
authors = ["Denis <den.scherbinin2018@yandex.ru>"]
readme = "README.md"
packages = [{include = "auto_testing_python"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
